// File: full_adder.v
// Generated by MyHDL 0.7
// Date: Mon Aug 15 23:46:58 2011


`timescale 1ns/10ps

module full_adder (
    A,
    B,
    C_in,
    Sum_out,
    C_out
);
// full adder circuit
// {A,B,C} --- inputs
// {Sum_out,C_out} -- outputs

input A;
input B;
input C_in;
output Sum_out;
wire Sum_out;
output C_out;
wire C_out;







assign Sum_out = ((A ^ B) ^ C_in);
assign C_out = ((A & B) ^ (C_in & (A ^ B)));

endmodule
